FROM centos

MAINTAINER geetika.talreja@nagarro.com

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat

RUN curl -O http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
RUN tar xvzf apache-tomcat-8.5.40.tar.gz
RUN pwd
RUN echo "$PWD"
RUN mv apache-tomcat-8.5.40/* /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps
#RUN curl -O -L https://github.com/AKSarav/SampleWebApp/raw/master/dist/SampleWebApp.war
RUN curl -O -L http://172.31.106.49:8081/artifactory/Maven_localRepo/0.0.1-SNAPSHOT/HelloProject-0.0.2-SNAPSHOT.war -u admin:password
EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]